<script lang="ts">
	// A model-area image that swaps between light and dark variants with the active
	// theme. `src` is the light image; the dark one is the same path with a `_dark`
	// suffix (both generated by the maps `domain-screenshots` script). Switching is
	// pure CSS via Tailwind's `dark:` variant, so it works without JS and during SSR.
	interface Props {
		src: string;
		alt?: string;
		class?: string;
	}

	let { src, alt = '', class: className = 'rounded-lg' }: Props = $props();

	const darkSrc = $derived(src.replace(/\.webp$/, '_dark.webp'));
</script>

<img {src} {alt} class="{className} dark:hidden" />
<img src={darkSrc} {alt} class="{className} hidden dark:block" />
