<script lang="ts" module>
	let imageSequence = 0;
</script>

<script lang="ts">
	import { untrack } from 'svelte';

	import XIcon from '@lucide/svelte/icons/x';

	import { cn } from '#lib/utils/ui.js';

	import * as Dialog from '#lib/components/ui/dialog/index.js';

	import { capNativeWidth } from '#lib/actions/cap-native-width.js';
	import { pinchZoom, zoomedSizes } from '#lib/actions/pinch-zoom.js';

	import { getZoomableImageGalleryContext } from './zoomable-image-gallery-context.js';

	import type { Snippet } from 'svelte';

	interface Props {
		src: string;
		alt: string;
		description?: string;
		class?: string;
		figureClass?: string;
		dialogImageClass?: string;
		captionClass?: string;
		hint?: string;
		width?: number | string;
		height?: number | string;
		/**
		 * Intrinsic widths (px) the image is available in, ascending: the first is
		 * `src` itself, every larger one lives next to it as `<name>-<width>w.webp`
		 * (the naming of the maps `domain-screenshots` source sets).
		 */
		widths?: number[];
		/** `sizes` hint for the preview, i.e. how wide it renders in the page. */
		sizes?: string;
		children?: Snippet;
		caption?: Snippet;
	}

	let {
		src,
		alt,
		description = alt,
		class: className,
		figureClass,
		dialogImageClass,
		captionClass,
		hint = 'Click to enlarge',
		width,
		height,
		widths,
		sizes,
		children,
		caption
	}: Props = $props();

	// The dark-theme variant lives next to the light one with a `_dark` suffix
	// (both generated by the maps `domain-screenshots` script). Swapping is pure CSS
	// via Tailwind's `dark:` variant, so it works without JS and during SSR.
	const darkSrc = $derived(src.replace(/\.webp$/, '_dark.webp'));

	const sourceSet = (base: string, widths: number[]) =>
		widths
			.map((w, i) => `${i === 0 ? base : base.replace(/\.webp$/, `-${w}w.webp`)} ${w}w`)
			.join(', ');
	const srcset = $derived(widths?.length ? sourceSet(src, widths) : undefined);
	const darkSrcset = $derived(widths?.length ? sourceSet(darkSrc, widths) : undefined);
	// Pinch-zoom level of the enlarged view, in half steps so `sizes` (and with it
	// the srcset candidate) only changes once the zoom has moved noticeably.
	let zoomScale = $state(1);

	// The enlarged view is capped by both viewport axes (the dialog's max-w-[96vw]
	// and max-h-[88vh]); with the intrinsic size known, the height cap translates
	// into a width so a wide screen does not fetch a larger file than it can show.
	const dialogSizes = $derived.by(() => {
		if (!srcset) return undefined;
		const ratio = Number(width) / Number(height);
		return Number.isFinite(ratio) && ratio > 0
			? `min(96vw, calc(88vh * ${ratio.toFixed(4)}))`
			: '96vw';
	});

	const gallery = getZoomableImageGalleryContext();
	const imageId = `zoomable-image-${++imageSequence}`;

	$effect(() => {
		if (!gallery) {
			return;
		}

		return untrack(() =>
			gallery.registerImage({
				id: imageId,
				src,
				darkSrc,
				srcset,
				darkSrcset,
				dialogSizes,
				alt,
				description,
				dialogImageClass
			})
		);
	});
</script>

{#snippet preview()}
	{#if children}
		{@render children()}
	{:else}
		<img
			{src}
			{srcset}
			{sizes}
			{alt}
			{width}
			{height}
			use:capNativeWidth
			loading="lazy"
			decoding="async"
			class={cn('block max-w-full rounded-lg dark:hidden', className)}
		/>
		<img
			src={darkSrc}
			srcset={darkSrcset}
			{sizes}
			{alt}
			{width}
			{height}
			use:capNativeWidth
			loading="lazy"
			decoding="async"
			class={cn('hidden max-w-full rounded-lg dark:block', className)}
		/>
	{/if}
	<span
		aria-hidden="true"
		class="pointer-events-none absolute inset-x-3 bottom-3 inline-flex w-fit max-w-[calc(100%-1.5rem)] rounded-full bg-black/70 px-3 py-1 text-sm font-medium text-white opacity-0 transition-opacity duration-200 group-hover:opacity-100 group-focus-within:opacity-100"
	>
		{hint}
	</span>
{/snippet}

{#if gallery}
	<figure class={cn(figureClass)}>
		<button
			type="button"
			aria-label={`Open full size image: ${alt}`}
			title={hint}
			onclick={() => gallery.openImage(imageId)}
			class="group ring-offset-background focus-visible:ring-ring relative block w-full cursor-zoom-in overflow-hidden rounded-lg focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-offset-2"
		>
			{@render preview()}
		</button>

		{#if caption}
			<figcaption class={cn('mt-2 text-sm', captionClass ?? 'text-muted-foreground')}>
				{@render caption()}
			</figcaption>
		{/if}
	</figure>
{:else}
	<Dialog.Root>
		<figure class={cn(figureClass)}>
			<Dialog.Trigger
				type="button"
				aria-label={`Open full size image: ${alt}`}
				title={hint}
				class="group ring-offset-background focus-visible:ring-ring relative block w-full cursor-zoom-in overflow-hidden rounded-lg focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-offset-2"
			>
				{@render preview()}
			</Dialog.Trigger>

			{#if caption}
				<figcaption class={cn('mt-2 text-sm', captionClass ?? 'text-muted-foreground')}>
					{@render caption()}
				</figcaption>
			{/if}
		</figure>

		<Dialog.Content
			aria-label={alt}
			showCloseButton={false}
			class="w-auto max-w-[96vw] gap-0 border-none bg-transparent p-0 shadow-none sm:max-w-[96vw]"
		>
			<!-- The zoomed image is viewed through this frame, so it never spills over
			     the chrome sitting on the frame's corners. `overflow-clip`, not hidden:
			     a scroll container would get a zero minimum width as a grid item and let
			     the dialog (a fixed box at left 50%, so shrink-to-fit only sees 50vw)
			     collapse to half the screen instead of sizing to the image. -->
			<div class="relative overflow-clip rounded-lg">
				<Dialog.Close
					class="focus-visible:ring-ring absolute top-3 right-3 z-10 inline-flex cursor-pointer items-center justify-center rounded-full bg-black/70 p-2 text-white transition hover:bg-black/85 focus-visible:outline-hidden focus-visible:ring-2"
					aria-label="Close image viewer"
				>
					<XIcon class="size-5" />
				</Dialog.Close>

				<div use:pinchZoom={{ onchange: (scale) => (zoomScale = Math.ceil(scale * 2) / 2) }}>
					<img
						{src}
						{srcset}
						sizes={zoomedSizes(dialogSizes, zoomScale)}
						{alt}
						loading="eager"
						decoding="async"
						draggable="false"
						class={cn(
							'block max-h-[88vh] w-auto max-w-[96vw] rounded-lg object-contain dark:hidden',
							dialogImageClass
						)}
					/>
					<img
						src={darkSrc}
						srcset={darkSrcset}
						sizes={zoomedSizes(dialogSizes, zoomScale)}
						{alt}
						loading="eager"
						decoding="async"
						draggable="false"
						class={cn(
							'hidden max-h-[88vh] w-auto max-w-[96vw] rounded-lg object-contain dark:block',
							dialogImageClass
						)}
					/>
				</div>
			</div>
		</Dialog.Content>
	</Dialog.Root>
{/if}
