export const swiftInstallCode = `<pre class="shiki material-theme-lighter" style="background-color:#FAFAFA;color:#90A4AE" tabindex="0">
<span class="line"><span style="color:#90A4AE">dependencies</span><span style="color:#39ADB5">:</span><span style="color:#90A4AE"> [</span></span>
<span class="line"><span style="color:#90A4AE">	.</span><span style="color:#6182B8">package</span><span style="color:#39ADB5">(</span><span style="color:#6182B8">url</span><span style="color:#39ADB5">:</span><span style="color:#39ADB5"> "</span><span style="color:#91B859">https://github.com/open-meteo/sdk.git</span><span style="color:#39ADB5">"</span><span style="color:#90A4AE">, </span><span style="color:#6182B8">from</span><span style="color:#39ADB5">:</span><span style="color:#39ADB5"> "</span><span style="color:#91B859">1.5.0</span><span style="color:#39ADB5">"</span><span style="color:#39ADB5">)</span></span>
<span class="line"><span style="color:#90A4AE">],</span></span>
<span class="line"><span style="color:#90A4AE">targets</span><span style="color:#39ADB5">:</span><span style="color:#90A4AE"> [</span></span>
<span class="line"><span style="color:#90A4AE">	.</span><span style="color:#6182B8">target</span><span style="color:#39ADB5">(</span><span style="color:#6182B8">name</span><span style="color:#39ADB5">:</span><span style="color:#39ADB5"> "</span><span style="color:#91B859">MyApp</span><span style="color:#39ADB5">"</span><span style="color:#90A4AE">, </span><span style="color:#6182B8">dependencies</span><span style="color:#39ADB5">:</span><span style="color:#90A4AE"> [</span></span>
<span class="line"><span style="color:#90A4AE">		.</span><span style="color:#6182B8">product</span><span style="color:#39ADB5">(</span><span style="color:#6182B8">name</span><span style="color:#39ADB5">:</span><span style="color:#39ADB5"> "</span><span style="color:#91B859">OpenMeteoSdk</span><span style="color:#39ADB5">"</span><span style="color:#90A4AE">, </span><span style="color:#6182B8">package</span><span style="color:#39ADB5">:</span><span style="color:#39ADB5"> "</span><span style="color:#91B859">sdk</span><span style="color:#39ADB5">"</span><span style="color:#39ADB5">)</span><span style="color:#90A4AE">,</span></span>
<span class="line"><span style="color:#90A4AE">	]</span><span style="color:#39ADB5">)</span></span>
<span class="line"><span style="color:#90A4AE">]</span></span></code></pre>`;
