<script lang="ts">
	import LicenseSelector from '../LicenseSelector.svelte';
	import ResultPreview from '../ResultPreview.svelte';
	import { urlHashStore } from '$lib/url-hash-store';
	import { fade, slide } from 'svelte/transition';
	import CalendarEvent from 'svelte-bootstrap-icons/lib/CalendarEvent.svelte';
	import Clock from 'svelte-bootstrap-icons/lib/Clock.svelte';
	import StartEndDate from '../StartEndDate.svelte';
	import LocationSelection from '../LocationSelection.svelte';
	import AccordionItem from '$lib/Elements/AccordionItem.svelte';
	import { countVariables } from '$lib/meteo';

	const defaultParameter = {
		current: [],
		hourly: [],
		daily: [],
		location_mode: 'location_search',
		csv_coordinates: '',
		length_unit: 'metric',
		timeformat: 'iso8601',
		timezone: 'UTC',
		past_days: '0',
		past_hours: '',
		forecast_days: '7',
		forecast_hours: '',
		start_date: '',
		end_date: '',
		time_mode: 'forecast_days',
		models: []
	};

	const params = urlHashStore({
		latitude: [54.544587],
		longitude: [10.227487],
		...defaultParameter,
		hourly: ['wave_height']
	});

	$: timezoneInvalid = $params.timezone == 'UTC' && $params.daily.length > 0;

	const hourly = [
		[
			{ name: 'wave_height', label: 'Wave Height' },
			{ name: 'wave_direction', label: 'Wave Direction' },
			{ name: 'wave_period', label: 'Wave Period' }
		],
		[
			{ name: 'wind_wave_height', label: 'Wind Wave Height' },
			{ name: 'wind_wave_direction', label: 'Wind Wave Direction' },
			{ name: 'wind_wave_period', label: 'Wind Wave Period' },
			{ name: 'wind_wave_peak_period', label: 'Wind Wave Peak Period' }
		],
		[
			{ name: 'swell_wave_height', label: 'Swell Wave Height' },
			{ name: 'swell_wave_direction', label: 'Swell Wave Direction' },
			{ name: 'swell_wave_period', label: 'Swell Wave Period' },
			{ name: 'swell_wave_peak_period', label: 'Swell Wave Peak Period' }
		]
	];

	const daily = [
		[
			{ name: 'wave_height_max', label: 'Wave Height Max' },
			{ name: 'wave_direction_dominant', label: 'Wave Direction Dominant' },
			{ name: 'wave_period_max', label: 'Wave Period Max' }
		],
		[
			{ name: 'wind_wave_height_max', label: 'Wind Wave Height Max' },
			{ name: 'wind_wave_direction_dominant', label: 'Wind Wave Direction Dominant' },
			{ name: 'wind_wave_period_max', label: 'Wind Wave Period Max' },
			{ name: 'wind_wave_peak_period_max', label: 'Wind Wave Peak Period Max' }
		],
		[
			{ name: 'swell_wave_height_max', label: 'Swell Wave Height Max' },
			{ name: 'swell_wave_direction_dominant', label: 'Swell Wave Direction Dominant' },
			{ name: 'swell_wave_period_max', label: 'Swell Wave Period Max' },
			{ name: 'swell_wave_peak_period_max', label: 'Swell Wave Peak Period Max' }
		]
	];

	let models = [
		[
			{ name: 'best_match', label: 'Best match', caption: 'EWAM & GWAM' },
		],[
			{ name: 'ewam', label: 'DWD EWAM', caption: '0.05° only Europe' },
			{ name: 'gwam', label: 'DWD GWAM', caption: '0.25°' },
			{ name: 'era5_ocean', label: 'ERA5-Ocean', caption: '0.5°, data from 1940 onwards' },
		]
	];
</script>

<svelte:head>
	<title>🌊 Marine Weather API | Open-Meteo.com</title>
	<link rel="canonical" href="https://open-meteo.com/en/docs/marine-weather-api" />
	<meta
		name="description"
		content="Marine Weather API with ocean wave forecasts. Free access for non-commercial use. Access detailed ocean wave forecasts generated by local and global models. Stay informed about wave conditions and make well-informed decisions for your marine activities. Enhance safety and optimize your maritime operations with accurate and reliable marine weather data."
	/>
</svelte:head>

<form method="get" action="https://marine-api.open-meteo.com/v1/marine">
	<LocationSelection
		bind:latitude={$params.latitude}
		bind:longitude={$params.longitude}
		bind:location_mode={$params.location_mode}
		bind:csv_coordinates={$params.csv_coordinates}
		bind:timezone={$params.timezone}
	/>

	<div class="row py-3 px-0">
		<div>
			<ul class="nav nav-underline" id="pills-tab" role="tablist">
				<li class="nav-item" role="presentation" style="width: 70px;">
					<span class="nav-link disabled" aria-disabled="true">Time:</span>
				</li>
				<li class="nav-item" role="presentation">
					<button
						class="nav-link"
						class:active={$params.time_mode == 'forecast_days'}
						id="pills-forecast_days-tab"
						type="button"
						role="tab"
						aria-controls="pills-forecast_days"
						aria-selected="true"
						on:click={() => ($params.time_mode = 'forecast_days')}><Clock/> Forecast Length</button
					>
				</li>
				<li class="nav-item" role="presentation">
					<button
						class="nav-link"
						class:active={$params.time_mode == 'time_interval'}
						id="pills-time_interval-tab"
						type="button"
						role="tab"
						aria-controls="pills-time_interval"
						on:click={() => ($params.time_mode = 'time_interval')}
						aria-selected="true"><CalendarEvent/> Time Interval</button
					>
				</li>
			</ul>
		</div>
		<div class="tab-content py-3" id="pills-tabContent">
			{#if $params.time_mode == 'forecast_days'}
				<div
					class="tab-pane active"
					in:fade
					id="pills-forecast_days"
					role="tabpanel"
					aria-labelledby="pills-forecast_days-tab"
					tabindex="0"
				>
					<div class="row">
						<div class="col-md-3">
							<div class="form-floating mb-3">
								<select
									class="form-select"
									name="forecast_days"
									id="forecast_days"
									aria-label="Forecast days"
									bind:value={$params.forecast_days}
								>
									<option value="1">1 day</option>
									<option value="3">3 days</option>
									<option value="5">5 days</option>
									<option value="7">7 days (default)</option>
									<option value="8">8 days</option>
								</select>
								<label for="forecast_days">Forecast days</label>
							</div>
						</div>
						<div class="col-md-3">
							<div class="form-floating mb-3">
								<select
									class="form-select"
									name="past_days"
									id="past_days"
									aria-label="Past days"
									bind:value={$params.past_days}
								>
									<option value="0">0 (default)</option>
									<option value="1">1</option>
									<option value="2">2</option>
									<option value="3">3</option>
									<option value="5">5</option>
									<option value="7">1 week</option>
									<option value="14">2 weeks</option>
									<option value="31">1 month</option>
									<option value="61">2 months</option>
									<option value="92">3 months</option>
								</select>
								<label for="past_days">Past days</label>
							</div>
						</div>
					</div>
				</div>
			{/if}
			{#if $params.time_mode == 'time_interval'}
				<div
					class="tab-pane active"
					in:fade
					id="pills-time_interval"
					role="tabpanel"
					aria-labelledby="pills-time_interval-tab"
					tabindex="0"
				>
					<div class="row">
						<div class="col-md-6 mb-3">
							<StartEndDate bind:start_date={$params.start_date} bind:end_date={$params.end_date}/>
						</div>
					</div>
				</div>
			{/if}
		</div>
	</div>

	<div class="row py-3 px-0">
		<h2>Hourly Marine Variables</h2>
		{#each hourly as group}
			<div class="col-md-4">
				{#each group as e}
					<div class="form-check">
						<input
							class="form-check-input"
							type="checkbox"
							value={e.name}
							id="{e.name}_hourly"
							name="hourly"
							bind:group={$params.hourly}
						/>
						<label class="form-check-label" for="{e.name}_hourly">{e.label}</label>
					</div>
				{/each}
			</div>
		{/each}
	</div>

	<div class="row py-3 px-0">
		<div class="accordion" id="accordionVariables">
			<AccordionItem
				id="models"
				title="Wave Models"
				count={countVariables(models, $params.models)}
			>
				{#each models as group}
					<div class="col-md-6 mb-3">
						{#each group as e}
							<div class="form-check">
								<input
									class="form-check-input"
									type="checkbox"
									value={e.name}
									id="{e.name}_model"
									name="models"
									bind:group={$params.models}
								/>
								<label class="form-check-label" for="{e.name}_model"
									>{e.label}&nbsp;<span class="text-muted">({e.caption})</span></label
								>
							</div>
						{/each}
					</div>
				{/each}
			</AccordionItem>
			<AccordionItem
				id="additional-variables"
				title="Additional Options"
			>
				<div class="col-md-12 mb-3">
					<small class="text-muted"
						>Note: You can further adjust the forecast time range for hourly weather variables using <mark>&forecast_hours=</mark> and <mark>&past_hours=</mark> as shown below.
				</div>
				<div class="col-md-3">
					<div class="form-floating mb-3">
						<select
							class="form-select"
							name="forecast_hours"
							id="forecast_hours"
							aria-label="Forecast Hours"
							bind:value={$params.forecast_hours}
						>
							<option value="">- (default)</option>
							<option value="1">1 hour</option>
							<option value="6">6 hours</option>
							<option value="12">12 hours</option>
							<option value="24">24 hours</option>
						</select>
						<label for="forecast_hours">Forecast Hours</label>
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-floating mb-3">
						<select
							class="form-select"
							name="past_hours"
							id="past_hours"
							aria-label="Past Hours"
							bind:value={$params.past_hours}
						>
							<option value="">- (default)</option>
							<option value="1">1 hour</option>
							<option value="6">6 hours</option>
							<option value="12">12 hours</option>
							<option value="24">24 hours</option>
						</select>
						<label for="past_hours">Past Hours</label>
					</div>
				</div>
			</AccordionItem>
		</div>
	</div>

	<div class="row py-3 px-0">
		<h2>Daily Marine Variables</h2>
		{#each daily as group}
			<div class="col-md-4">
				{#each group as e}
					<div class="form-check">
						<input
							class="form-check-input"
							type="checkbox"
							value={e.name}
							id="{e.name}_daily"
							name="daily"
							bind:group={$params.daily}
						/>
						<label class="form-check-label" for="{e.name}_daily">{e.label}</label>
					</div>
				{/each}
			</div>
		{/each}
		{#if timezoneInvalid}
		<div class="alert alert-warning" role="alert">
			It is recommended to select a timezone for daily data. Per default the API will use GMT+0.
		</div>
		{/if}
	</div>

	<div class="row py-3 px-0">
		<h2>Current Conditions</h2>
		{#each hourly as group}
			<div class="col-md-3 mb-2">
				{#each group as e}
					<div class="form-check">
						<input
							class="form-check-input"
							type="checkbox"
							value={e.name}
							id="{e.name}_current"
							name="current"
							bind:group={$params.current}
						/>
						<label class="form-check-label" for="{e.name}_current">{e.label}</label>
					</div>
				{/each}
			</div>
		{/each}
	</div>

	<div class="row py-3 px-0">
		<h2>Settings</h2>
		<div class="col-md-3">
			<div class="form-floating mb-3">
				<select
					class="form-select"
					name="length_unit"
					id="length_unit"
					aria-label="Length Unit"
					bind:value={$params.length_unit}
				>
					<option value="metric">Metric</option>
					<option value="imperial">Imperial</option>
				</select>
				<label for="length_unit">Length Unit</label>
			</div>
		</div>
		<div class="col-md-3">
			<div class="form-floating mb-3">
				<select
					class="form-select"
					name="timeformat"
					id="timeformat"
					aria-label="Timeformat"
					bind:value={$params.timeformat}
				>
					<option value="iso8601">ISO 8601 (e.g. 2022-12-31)</option>
					<option value="unixtime">Unix timestamp</option>
				</select>
				<label for="timeformat">Timeformat</label>
			</div>
		</div>
	</div>

	<LicenseSelector />
</form>

<ResultPreview {params} {defaultParameter} useStockChart type="marine" action="marine" sdk_type="marine_api"/>

<h2 id="data-sources" class="mt-5">Data Sources</h2>
<div class="row">
	<div class="col-6">
		<p>
			The Marine API combines wave models from different sources.
		</p>
	</div>
	<div class="col-6">
	</div>
</div>
<div class="table-responsive">
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Data Set</th>
				<th scope="col">Region</th>
				<th scope="col">Spatial Resolution</th>
				<th scope="col">Temporal Resolution</th>
				<th scope="col">Data Availability</th>
				<th scope="col">Update frequency</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th scope="row"
					><a
						href="https://www.dwd.de/EN/specialusers/shipping/seegangsvorhersagesystem_en.html"
						>DWD GWAM</a
					>
				</th>
				<td>Europe</td>
				<td>0.05° (~25 km)</td>
				<td>Hourly</td>
				<td>August 2022 with 8 day forecast</td>
				<td>Twice daily</td>
			</tr>
			<tr>
				<th scope="row"
					><a
						href="https://www.dwd.de/EN/specialusers/shipping/seegangsvorhersagesystem_en.html"
						>DWD EWAM</a
					>
				</th>
				<td>Global</td>
				<td>0.25° (~25 km)</td>
				<td>Hourly</td>
				<td>August 2022 with 4 day forecast</td>
				<td>Twice daily</td>
			</tr>
			<tr>
				<th scope="row"
					><a
						href="https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=overview"
						>ERA5-Ocean</a
					>
				</th>
				<td>Global</td>
				<td>0.5° (~50 km)</td>
				<td>Hourly</td>
				<td>1940 to present</td>
				<td>Daily with 5 days delay</td>
			</tr>
		</tbody>
	</table>
</div>

<div class="col-12 py-5">
	<h2 id="api-documentation">API Documentation</h2>
	<p>
		The API endpoint <mark>/v1/marine</mark> accepts a geographical coordinate, a list of weather variables
		and responds with a JSON hourly marine weather forecast for 7 days. Time always starts at 0:00 today.
		All URL parameters are listed below:
	</p>
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">Parameter</th>
					<th scope="col">Format</th>
					<th scope="col">Required</th>
					<th scope="col">Default</th>
					<th scope="col">Description</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="row">latitude, longitude</th>
					<td>Floating point</td>
					<td>Yes</td>
					<td />
					<td
						>Geographical WGS84 coordinates of the location. Multiple coordinates can be comma
						separated. E.g. <mark>&latitude=52.52,48.85&longitude=13.41,2.35</mark>. To return data
						for multiple locations the JSON output changes to a list of structures. CSV and XLSX
						formats add a column <mark>location_id</mark>.</td
					>
				</tr>
				<tr>
					<th scope="row">hourly</th>
					<td>String array</td>
					<td>No</td>
					<td />
					<td
						>A list of weather variables which should be returned. Values can be comma separated, or
						multiple
						<mark>&hourly=</mark> parameter in the URL can be used.
					</td>
				</tr>
				<tr>
					<th scope="row">daily</th>
					<td>String array</td>
					<td>No</td>
					<td />
					<td
						>A list of daily weather variable aggregations which should be returned. Values can be
						comma separated, or multiple <mark>&daily=</mark> parameter in the URL can be used. If
						daily weather variables are specified, parameter <mark>timezone</mark> is required.</td
					>
				</tr>
				<tr>
					<th scope="row">current</th>
					<td>String array</td>
					<td>No</td>
					<td />
					<td>A list of variables to get current conditions.</td>
				</tr>
				<tr>
					<th scope="row">timeformat</th>
					<td>String</td>
					<td>No</td>
					<td><mark>iso8601</mark></td>
					<td
						>If format <mark>unixtime</mark> is selected, all time values are returned in UNIX epoch
						time in seconds. Please note that all timestamp are in GMT+0! For daily values with unix
						timestamps, please apply
						<mark>utc_offset_seconds</mark> again to get the correct date.
					</td>
				</tr>
				<tr>
					<th scope="row">timezone</th>
					<td>String</td>
					<td>No</td>
					<td><mark>GMT</mark></td>
					<td
						>If <mark>timezone</mark> is set, all timestamps are returned as local-time and data is
						returned starting at 00:00 local-time. Any time zone name from the
						<a href="https://en.wikipedia.org/wiki/List_of_tz_database_time_zones" target="_blank"
							>time zone database</a
						>
						is supported. If <mark>auto</mark> is set as a time zone, the coordinates will be automatically
						resolved to the local time zone. For multiple coordinates, a comma separated list of timezones
						can be specified.</td
					>
				</tr>
				<tr>
					<th scope="row">past_days</th>
					<td>Integer (0-92)</td>
					<td>No</td>
					<td><mark>0</mark></td>
					<td
						>If <mark>past_days</mark> is set, yesterday or the day before yesterday data are also returned.</td
					>
				</tr>
				<tr>
					<th scope="row">forecast_days</th>
					<td>Integer (0-8)</td>
					<td>No</td>
					<td><mark>5</mark></td>
					<td>Per default, 7 days are returned. Up to 8 days of forecast are possible.</td>
				</tr>
				<tr>
					<th scope="row">forecast_hours<br />past_hours</th>
					<td>Integer (&gt;0)</td>
					<td>No</td>
					<td></td>
					<td>Similar to forecast_days, the number of timesteps of hourly data can controlled. Instead of using the current day as a reference, the current hour is used. </td>
				</tr>
				<tr>
					<th scope="row">start_date<br />end_date</th>
					<td>String (yyyy-mm-dd)</td>
					<td>No</td>
					<td />
					<td
						>The time interval to get weather data. A day must be specified as an ISO8601 date (e.g.
						<mark>2022-06-30</mark>).
					</td>
				</tr>
				<tr>
					<th scope="row">start_hour<br />end_hour</th>
					<td>String (yyyy-mm-ddThh:mm)</td>
					<td>No</td>
					<td />
					<td
						>The time interval to get weather data for hourly data. Time must be specified as an ISO8601 date (e.g.
						<mark>2022-06-30T12:00</mark>).
					</td>
				</tr>
				<tr>
					<th scope="row">length_unit</th>
					<td>String</td>
					<td>No</td>
					<td><mark>metric</mark></td>
					<td>Options <mark>metric</mark> and <mark>imperial</mark></td>
				</tr>
				<tr>
					<th scope="row">cell_selection</th>
					<td>String</td>
					<td>No</td>
					<td><mark>sea</mark></td>
					<td
						>Set a preference how grid-cells are selected. The default <mark>land</mark> finds a
						suitable grid-cell on land with
						<a
							href="https://openmeteo.substack.com/p/improving-weather-forecasts-with"
							title="Elevation based grid-cell selection explained"
							>similar elevation to the requested coordinates using a 90-meter digital elevation
							model</a
						>.
						<mark>sea</mark> prefers grid-cells on sea. <mark>nearest</mark> selects the nearest possible
						grid-cell.
					</td>
				</tr>
				<tr>
					<th scope="row">apikey</th>
					<td>String</td>
					<td>No</td>
					<td />
					<td
						>Only required to commercial use to access reserved API resources for customers. The
						server URL requires the prefix <mark>customer-</mark>. See
						<a href="/en/pricing" title="Pricing information to use the weather API commercially"
							>pricing</a
						> for more information.</td
					>
				</tr>
			</tbody>
		</table>
	</div>
	<p>
		Additional optional URL parameters will be added. For API stability, no required parameters will
		be added in the future!
	</p>

	<h3 class="mt-5">Hourly Parameter Definition</h3>
	<p>
		The parameter <mark>&hourly=</mark> accepts the following values. Most weather variables are given
		as an instantaneous value for the indicated hour. Some variables like precipitation are calculated
		from the preceding hour as an average or sum.
	</p>
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">Variable</th>
					<th scope="col">Valid time</th>
					<th scope="col">Unit</th>
					<th scope="col">Description</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="row">wave_height<br />wind_wave_height<br />swell_wave_height</th>
					<td>Instant</td>
					<td>Meter</td>
					<td>Wave height of significant mean, wind and swell waves</td>
				</tr>
				<tr>
					<th scope="row">wave_direction<br />wind_wave_direction<br />swell_wave_direction</th>
					<td>Instant</td>
					<td>°</td>
					<td>Mean direction of mean, wind and swell waves</td>
				</tr>
				<tr>
					<th scope="row">wave_period<br />wind_wave_period<br />swell_wave_period</th>
					<td>Instant</td>
					<td>Seconds</td>
					<td>Period between mean, wind and swell waves.</td>
				</tr>
				<tr>
					<th scope="row">wind_wave_peak_period<br />swell_wave_peak_period</th>
					<td>Instant</td>
					<td>Seconds</td>
					<td>Peak period between wind and swell waves.</td>
				</tr>
			</tbody>
		</table>
	</div>

	<h3 class="mt-5">Daily Parameter Definition</h3>
	<p>
		Aggregations are a simple 24 hour aggregation from hourly values. The parameter <mark
			>&daily=</mark
		> accepts the following values:
	</p>
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">Variable</th>
					<th scope="col">Unit</th>
					<th scope="col">Description</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="row">wave_height_max<br />wind_wave_height_max<br />swell_wave_height_max</th>
					<td>Meter</td>
					<td>Maximum wave height on a given day for mean, wind and swell waves</td>
				</tr>
				<tr>
					<th scope="row"
						>wave_direction_dominant<br />wind_wave_direction_dominant<br
						/>swell_wave_direction_dominant
					</th>
					<td>°</td>
					<td>Dominant wave direction of mean, wind and swell waves</td>
				</tr>
				<tr>
					<th scope="row">wave_period_max<br />wind_wave_period_max<br />swell_wave_period_max</th>
					<td>Seconds</td>
					<td>Maximum wave period of mean, wind and swell</td>
				</tr>
				<tr>
					<th scope="row">wind_wave_peak_period_max<br />swell_wave_peak_period_max</th>
					<td>Seconds</td>
					<td>Maximum peak period between wind and swell waves.</td>
				</tr>
			</tbody>
		</table>
	</div>

	<h3 class="mt-5">JSON Return Object</h3>
	<p>On success a JSON object will be returned.</p>
	<pre>
      <code>
{`
  "latitude": 52.52,
  "longitude": 13.419,
  "elevation": 44.812,
  "generationtime_ms": 2.2119,
  "utc_offset_seconds": 0,
  "timezone": "Europe/Berlin",
  "timezone_abbreviation": "CEST",
  "hourly": {
    "time": ["2022-07-01T00:00", "2022-07-01T01:00", "2022-07-01T02:00", ...],
    "wave_height": [1, 1.7, 1.7, 1.5, 1.5, 1.8, 2.0, 1.9, 1.3, ...]
  },
  "hourly_units": {
    "wave_height": "m"
  },
`}
      </code>
    </pre>
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">Parameter</th>
					<th scope="col">Format</th>
					<th scope="col">Description</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="row">latitude, longitude</th>
					<td>Floating point</td>
					<td
						>WGS84 of the center of the weather grid-cell which was used to generate this forecast.
						This coordinate might be a few kilometers away from the requested coordinate.</td
					>
				</tr>
				<tr>
					<th scope="row">generationtime_ms</th>
					<td>Floating point</td>
					<td
						>Generation time of the weather forecast in milliseconds. This is mainly used for
						performance monitoring and improvements.</td
					>
				</tr>
				<tr>
					<th scope="row">utc_offset_seconds</th>
					<td>Integer</td>
					<td>Applied timezone offset from the <mark>&timezone=</mark> parameter.</td>
				</tr>
				<tr>
					<th scope="row">timezone<br />timezone_abbreviation</th>
					<td>String</td>
					<td
						>Timezone identifier (e.g. <mark>Europe/Berlin</mark>) and abbreviation (e.g.
						<mark>CEST</mark>)</td
					>
				</tr>
				<tr>
					<th scope="row">hourly</th>
					<td>Object</td>
					<td
						>For each selected weather variable, data will be returned as a floating point array.
						Additionally a
						<mark>time</mark> array will be returned with ISO8601 timestamps.
					</td>
				</tr>
				<tr>
					<th scope="row">hourly_units</th>
					<td>Object</td>
					<td>For each selected weather variable, the unit will be listed here.</td>
				</tr>
				<tr>
					<th scope="row">daily</th>
					<td>Object</td>
					<td
						>For each selected daily weather variable, data will be returned as a floating point
						array. Additionally a <mark>time</mark> array will be returned with ISO8601 timestamps.</td
					>
				</tr>
				<tr>
					<th scope="row">daily_units</th>
					<td>Object</td>
					<td>For each selected daily weather variable, the unit will be listed here.</td>
				</tr>
			</tbody>
		</table>
	</div>
	<h3 class="mt-5">Errors</h3>
	<p>
		In case an error occurs, for example a URL parameter is not correctly specified, a JSON error
		object is returned with a HTTP 400 status code.
	</p>
	<pre>
      <code>
{`
  "error": true,
  "reason": "Cannot initialize WeatherVariable from invalid String value tempeture_2m for key hourly"
`}
      </code>
    </pre>
</div>

<h2 id="citation">Citation & Acknowledgement</h2>
<p>
	Generated using ICON Wave forecast from the <a
		href="https://www.dwd.de/EN/service/copyright/copyright_node.html"
		target="_blank">German Weather Service DWD</a
	>.
</p>
<p>
	All users of Open-Meteo data must provide a clear attribution to DWD as well as a reference to
	Open-Meteo.
</p>
