<<<<<<< HEAD
import { ecmwf_aifs_europe_variables, ecmwf_ifs_europe_variables } from '../ensemble-api/options';

export const defaultParameters = {
	daily: [],
	hourly: [],
	models: [],
	current: [],

	timezone: 'UTC',
	location_mode: 'location_search',
	csv_coordinates: undefined,

	time_mode: 'forecast_days',
	past_days: '0',
	forecast_days: '7',

	end_date: undefined,
	start_date: undefined,

	past_hours: undefined,
	cell_selection: undefined,
	forecast_hours: undefined,
	temporal_resolution: undefined,

	tilt: '0',
	azimuth: '0',

	timeformat: 'iso8601',
	wind_speed_unit: 'kmh',
	precipitation_unit: 'mm',
	temperature_unit: 'celsius'
};

export const pressureVariables = [
	{ value: 'temperature', label: 'Temperature' },
	{ value: 'relative_humidity', label: 'Relative Humidity' },
	{ value: 'dew_point', label: 'Dew Point' },
	{ value: 'cloud_cover', label: 'Cloud Cover' },
	{ value: 'wind_speed', label: 'Wind Speed' },
	{ value: 'wind_direction', label: 'Wind Direction' },
	{ value: 'vertical_velocity', label: 'Vertical Velocity' },
	{ value: 'geopotential_height', label: 'Geopotential Height' }
];

export const levels = [1000, 925, 850, 700, 600, 500, 400, 300, 250, 200, 150, 100, 50];

const ecmwf_pressure_levels = [
	'cloud_cover_1000hPa',
	'cloud_cover_100hPa',
	'cloud_cover_150hPa',
	'cloud_cover_200hPa',
	'cloud_cover_250hPa',
	'cloud_cover_300hPa',
	'cloud_cover_400hPa',
	'cloud_cover_500hPa',
	'cloud_cover_50hPa',
	'cloud_cover_600hPa',
	'cloud_cover_700hPa',
	'cloud_cover_850hPa',
	'cloud_cover_925hPa',
	'dew_point_1000hPa',
	'dew_point_100hPa',
	'dew_point_150hPa',
	'dew_point_200hPa',
	'dew_point_250hPa',
	'dew_point_300hPa',
	'dew_point_400hPa',
	'dew_point_500hPa',
	'dew_point_50hPa',
	'dew_point_600hPa',
	'dew_point_700hPa',
	'dew_point_850hPa',
	'dew_point_925hPa',
	'geopotential_height_1000hPa',
	'geopotential_height_100hPa',
	'geopotential_height_150hPa',
	'geopotential_height_200hPa',
	'geopotential_height_250hPa',
	'geopotential_height_300hPa',
	'geopotential_height_400hPa',
	'geopotential_height_500hPa',
	'geopotential_height_50hPa',
	'geopotential_height_600hPa',
	'geopotential_height_700hPa',
	'geopotential_height_850hPa',
	'geopotential_height_925hPa',
	'relative_humidity_1000hPa',
	'relative_humidity_100hPa',
	'relative_humidity_150hPa',
	'relative_humidity_200hPa',
	'relative_humidity_250hPa',
	'relative_humidity_300hPa',
	'relative_humidity_400hPa',
	'relative_humidity_500hPa',
	'relative_humidity_50hPa',
	'relative_humidity_600hPa',
	'relative_humidity_700hPa',
	'relative_humidity_850hPa',
	'relative_humidity_925hPa',
	'temperature_1000hPa',
	'temperature_100hPa',
	'temperature_150hPa',
	'temperature_200hPa',
	'temperature_250hPa',
	'temperature_300hPa',
	'temperature_400hPa',
	'temperature_500hPa',
	'temperature_50hPa',
	'temperature_600hPa',
	'temperature_700hPa',
	'temperature_850hPa',
	'temperature_925hPa',
	'vertical_velocity_1000hPa',
	'vertical_velocity_100hPa',
	'vertical_velocity_150hPa',
	'vertical_velocity_200hPa',
	'vertical_velocity_250hPa',
	'vertical_velocity_300hPa',
	'vertical_velocity_400hPa',
	'vertical_velocity_500hPa',
	'vertical_velocity_50hPa',
	'vertical_velocity_600hPa',
	'vertical_velocity_700hPa',
	'vertical_velocity_850hPa',
	'vertical_velocity_925hPa',
	'wind_speed_1000hPa',
	'wind_speed_100hPa',
	'wind_speed_150hPa',
	'wind_speed_200hPa',
	'wind_speed_250hPa',
	'wind_speed_300hPa',
	'wind_speed_400hPa',
	'wind_speed_500hPa',
	'wind_speed_50hPa',
	'wind_speed_600hPa',
	'wind_speed_700hPa',
	'wind_speed_850hPa',
	'wind_speed_925hPa',
	'wind_direction_1000hPa',
	'wind_direction_100hPa',
	'wind_direction_150hPa',
	'wind_direction_200hPa',
	'wind_direction_250hPa',
	'wind_direction_300hPa',
	'wind_direction_400hPa',
	'wind_direction_500hPa',
	'wind_direction_50hPa',
	'wind_direction_600hPa',
	'wind_direction_700hPa',
	'wind_direction_850hPa',
	'wind_direction_925hPa'
];

export const icon_global_variables = [
	'weather_code',
	'temperature_2m',
	'surface_pressure',
	'pressure_msl',
	'relative_humidity_2m',
	'dew_point_2m',
	'apparent_temperature',
	'precipitation',
	'snowfall',
	'snowfall_water_equivalent',
	'cloud_cover',
	'et0_fao_evapotranspiration',
	'vapour_pressure_deficit',
	'wind_speed_10m',
	'wind_direction_10m',
	'rain',
	'wet_bulb_temperature_2m',
	'shortwave_radiation',
	'sunshine_duration',
	'is_day'
];

export const icon_eu_variables = [
	'weather_code',
	'temperature_2m',
	'surface_pressure',
	'pressure_msl',
	'precipitation',
	'snowfall',
	'snowfall_water_equivalent',
	'cloud_cover',
	'wind_speed_10m',
	'wind_direction_10m',
	'wind_gusts_10m',
	'wind_speed_80m',
	'wind_direction_80m',
	'temperature_80m',
	'rain',
	'cape',
	'wet_bulb_temperature_2m',
	'shortwave_radiation',
	'sunshine_duration',
	'is_day'
];

export const icon_d2_variables = [
	'weather_code',
	'temperature_2m',
	'surface_pressure',
	'pressure_msl',
	'relative_humidity_2m',
	'dew_point_2m',
	'apparent_temperature',
	'precipitation',
	'snowfall',
	'snowfall_water_equivalent',
	'cloud_cover',
	'et0_fao_evapotranspiration',
	'vapour_pressure_deficit',
	'wind_speed_10m',
	'wind_speed_80m',
	'wind_speed_180m',
	'wind_direction_10m',
	'wind_direction_80m',
	'wind_direction_180m',
	'wind_gusts_10m',
	'temperature_80m',
	'rain',
	'cape',
	'shortwave_radiation',
	'sunshine_duration',
	'wet_bulb_temperature_2m',
	'temperature_500hPa',
	'temperature_850hPa',
	'geopotential_height_500hPa',
	'geopotential_height_850hPa',
	'is_day'
];

export const gfs025_variables = [
	'temperature_2m',
	'visibility',
	'wind_gusts_10m',
	'surface_pressure',
	'pressure_msl',
	'soil_temperature_0_to_10cm',
	'soil_moisture_0_to_10cm',
	'snow_depth',
	'relative_humidity_2m',
	'dew_point_2m',
	'wind_speed_10m',
	'wind_direction_10m',
	'precipitation',
	'snowfall',
	'snowfall_water_equivalent',
	'cape',
	'cloud_cover',
	'wet_bulb_temperature_2m',
	'apparent_temperature',
	'weather_code',
	'et0_fao_evapotranspiration',
	'vapour_pressure_deficit',
	'cape',
	'convective_inhibition',
	'rain',
	'shortwave_radiation',
	'sunshine_duration',
	'is_day'
];

export const aigfs025_variables = [
	...ecmwf_pressure_levels,
	'temperature_2m',
	'surface_pressure',
	'pressure_msl',
	'wind_speed_10m',
	'wind_direction_10m',
	'precipitation',
	'rain',
	'snowfall',
	'snowfall_water_equivalent',
	'cloud_cover',
	'cloud_cover_high',
	'cloud_cover_low',
	'cloud_cover_mid',
	'weather_code',
	'is_day'
];

export const gfs05_variables = [
	...gfs025_variables,
	...ecmwf_pressure_levels,
	'snow_depth',
	'wind_speed_80m',
	'wind_direction_80m',
	'wind_speed_100m',
	'wind_direction_100m',
	'wind_speed_120m',
	'wind_direction_120m',
	'soil_temperature_10_to_40cm',
	'soil_temperature_40_to_100cm',
	'soil_temperature_100_to_200cm',
	'soil_moisture_10_to_40cm',
	'soil_moisture_40_to_100cm',
	'soil_moisture_100_to_200cm',
	'uv_index',
	'uv_index_clear_sky',
	'cape',
	'freezing_level_height',
	'rain',
	'wet_bulb_temperature_2m',
	'surface_temperature',
	'temperature_80m',
	'temperature_120m',
	'shortwave_radiation',
	'temperature_500hPa',
	'temperature_850hPa',
	'geopotential_height_500hPa',
	'geopotential_height_850hPa',
	'is_day'
];

export const ecmwf_ifs025_variables = [
	...ecmwf_pressure_levels,
	'cape',
	'cloud_cover',
	'cloud_cover_high',
	'cloud_cover_low',
	'cloud_cover_mid',
	'dew_point_2m',
	'precipitation',
	'precipitation_probability',
	'precipitation_type',
	'pressure_msl',
	'relative_humidity_2m',
	'runoff',
	'shortwave_radiation',
	'snow_depth',
	'snow_depth_water_equivalent',
	'snowfall_water_equivalent',
	'snowfall',
	'rain',
	'soil_moisture_0_to_7cm',
	'soil_moisture_100_to_255cm',
	'soil_moisture_28_to_100cm',
	'soil_moisture_7_to_28cm',
	'soil_temperature_0_to_7cm',
	'soil_temperature_100_to_255cm',
	'soil_temperature_28_to_100cm',
	'soil_temperature_7_to_28cm',
	'surface_temperature',
	'temperature_2m',
	'temperature_2m_max',
	'temperature_2m_min',
	'total_column_integrated_water_vapour',
	'wet_bulb_temperature_2m',
	'wind_gusts_10m',
	'wind_speed_100m',
	'wind_speed_10m',
	'wind_direction_100m',
	'wind_direction_10m',
	'apparent_temperature',
	'vapour_pressure_deficit',
	'weather_code',
	'sunshine_duration',
	'surface_pressure',
	'et0_fao_evapotranspiration',
	'is_day'
];

export const ecmwf_aifs025_variables = [
	...ecmwf_pressure_levels,
	'cloud_cover',
	'cloud_cover_high',
	'cloud_cover_low',
	'cloud_cover_mid',
	'dew_point_2m',
	'precipitation',
	'precipitation_probability',
	'pressure_msl',
	'relative_humidity_2m',
	'shortwave_radiation',
	'snowfall_water_equivalent',
	'snowfall',
	'rain',
	'soil_temperature_0_to_7cm',
	'soil_temperature_7_to_28cm',
	'surface_temperature',
	'temperature_2m',
	'wind_speed_100m',
	'wind_speed_10m',
	'wind_direction_100m',
	'wind_direction_10m',
	'wet_bulb_temperature_2m',
	'apparent_temperature',
	'vapour_pressure_deficit',
	'weather_code',
	'surface_pressure',
	'sunshine_duration',
	'et0_fao_evapotranspiration',
	'is_day'
];

export const ukmo_variables = [
	'temperature_2m',
	'rain',
	'snowfall',
	'snow_depth_water_equivalent',
	'snowfall_water_equivalent',
	'precipitation',
	'et0_fao_evapotranspiration',
	'relative_humidity_2m',
	'dew_point_2m',
	'apparent_temperature',
	'vapour_pressure_deficit',
	'weather_code',
	'surface_pressure',
	'pressure_msl',
	'cloud_cover',
	'wind_speed_10m',
	'wind_direction_10m',
	'wind_gusts_10m',
	'surface_temperature',
	'visibility',
	'cape',
	'wet_bulb_temperature_2m',
	'shortwave_radiation',
	'sunshine_duration',
	'is_day'
];

export const ukmo_2km_variables = [
	...ukmo_variables,
	'cloud_cover_high',
	'cloud_cover_mid',
	'cloud_cover_low',
	'is_day'
];
=======
import {
	aigfs025_variables,
	bom_access_global_ensemble,
	ecmwf_aifs025_variables,
	ecmwf_ifs025_variables,
	gfs025_variables,
	gfs05_variables,
	google_weathernext2_variables,
	icon_d2_variables,
	icon_eu_variables,
	icon_global_variables,
	meteoswiss_variables,
	ukmo_2km_variables,
	ukmo_variables
} from '../ensemble-options';
>>>>>>> origin/main

export const gem_global_variables = [
	'temperature_2m',
	'surface_pressure',
	'snow_depth',
	'relative_humidity_2m',
	'dew_point_2m',
	'wind_speed_10m',
	'wind_direction_10m',
	'precipitation',
	'snowfall',
	'snowfall_water_equivalent',
	'cape',
	'cloud_cover',
	'apparent_temperature',
	'weather_code',
	'pressure_msl',
	'et0_fao_evapotranspiration',
	'vapour_pressure_deficit',
	'cape',
	'rain',
	'wet_bulb_temperature_2m',
	'shortwave_radiation',
	'sunshine_duration',
	'temperature_500hPa',
	'temperature_850hPa',
	'geopotential_height_500hPa',
	'geopotential_height_850hPa',
	'is_day'
];

export const availableVariables = {
	dwd_icon_eps_ensemble_mean_seamless: icon_d2_variables,
	dwd_icon_eps_ensemble_mean: icon_global_variables,
	dwd_icon_eu_eps_ensemble_mean: icon_eu_variables,
	dwd_icon_d2_eps_ensemble_mean: icon_d2_variables,
	ncep_gefs_ensemble_mean_seamless: gfs05_variables,
	ncep_gefs025_ensemble_mean: gfs025_variables,
	ncep_gefs05_ensemble_mean: gfs05_variables,
	ncep_aigefs025_ensemble_mean: aigfs025_variables,
	ncep_hgefs025_ensemble_mean: gfs025_variables,
	ecmwf_ifs025_ensemble_mean: ecmwf_ifs025_variables,
	ecmwf_aifs025_ensemble_mean: ecmwf_aifs025_variables,
	ecmwf_ifs_europe_ensemble: ecmwf_ifs_europe_variables,
	ecmwf_aifs_europe_ensemble: ecmwf_aifs_europe_variables,
	ukmo_global_ensemble_mean_20km: ukmo_variables,
	ukmo_uk_ensemble_mean_2km: ukmo_2km_variables,
	cmc_gem_geps_ensemble_mean: gem_global_variables,
	bom_access_global_ensemble_mean: bom_access_global_ensemble,
	meteoswiss_icon_ch1_ensemble_mean: meteoswiss_variables,
	meteoswiss_icon_ch2_ensemble_mean: meteoswiss_variables,
	google_weathernext2_ensemble_mean: google_weathernext2_variables
};

export const models = [
	[
		{ value: 'dwd_icon_eps_ensemble_mean_seamless', label: 'DWD ICON EPS Seamless Mean' },
		{ value: 'dwd_icon_eps_ensemble_mean', label: 'DWD ICON EPS Global Mean' },
		{ value: 'dwd_icon_eu_eps_ensemble_mean', label: 'DWD ICON EPS EU Mean' },
		{ value: 'dwd_icon_d2_eps_ensemble_mean', label: 'DWD ICON EPS D2 Mean' }
	],
	[
		{ value: 'ncep_gefs_ensemble_mean_seamless', label: 'GFS Ensemble Seamless Mean' },
		{ value: 'ncep_gefs025_ensemble_mean', label: 'GFS Ensemble 0.25° Mean' },
		{ value: 'ncep_gefs05_ensemble_mean', label: 'GFS Ensemble 0.5° Mean' },
		{ value: 'ncep_aigefs025_ensemble_mean', label: 'AIGEFS 0.25° Mean' },
		{ value: 'ncep_hgefs025_ensemble_mean', label: 'HGEFS 0.25° Mean' }
	],
	[
		{ value: 'ecmwf_ifs025_ensemble_mean', label: 'ECMWF IFS 0.25° Ensemble Mean' },
		{ value: 'ecmwf_aifs025_ensemble_mean', label: 'ECMWF AIFS 0.25° Ensemble Mean' },
		{ value: 'ecmwf_ifs_europe_ensemble', label: 'ECMWF IFS Europe (O1280) Ensemble Mean' },
		{ value: 'ecmwf_aifs_europe_ensemble', label: 'ECMWF AIFS Europe (N320) Ensemble Mean' }
	],
	[
		{ value: 'ukmo_global_ensemble_mean_20km', label: 'UK MetOffice Global 20km Mean' },
		{ value: 'ukmo_uk_ensemble_mean_2km', label: 'UK MetOffice UK 2km Mean' },
		{ value: 'cmc_gem_geps_ensemble_mean', label: 'GEM Global Ensemble Mean' },
		{ value: 'bom_access_global_ensemble_mean', label: 'BOM ACCESS Global Mean' }
	],
	[
		{ value: 'meteoswiss_icon_ch1_ensemble_mean', label: 'MeteoSwiss ICON CH1 Mean' },
		{ value: 'meteoswiss_icon_ch2_ensemble_mean', label: 'MeteoSwiss ICON CH2 Mean' }
	],
	[{ value: 'google_weathernext2_ensemble_mean', label: 'Google WeatherNext 2 Ensemble Mean' }]
];

export const forecastDaysOptions = [
	{ value: '1', label: '1 day' },
	{ value: '3', label: '3 days' },
	{ value: '7', label: '7 days (default)' },
	{ value: '14', label: '14 days' },
	{ value: '16', label: '16 days' },
	{ value: '30', label: '30 days' },
	{ value: '35', label: '35 days' }
];

export const noSpreadVariables = ['is_day', 'weather_code'];
