// Generated by scripts/backgrounds.mjs - do not edit by hand.
//
// Intrinsic size and the generated width ladder of every background that has a
// high-resolution source. Backgrounds missing here have no variants and are
// served as the plain single-size file.
export interface BackgroundVariants {
	/** Width of the largest variant, in pixels. */
	width: number;
	/** Height of the largest variant, in pixels. */
	height: number;
	/** Widths available as `<name>-<width>.webp`, ascending. */
	widths: number[];
}

export const BACKGROUND_VARIANTS: Record<string, BackgroundVariants> = {
	'cirrus2.webp': { width: 3840, height: 1826, widths: [640, 960, 1280, 1920, 2560, 3840] },
	'edessa.webp': { width: 3840, height: 1444, widths: [640, 960, 1280, 1920, 2560, 3840] },
	'fluelapass.webp': { width: 3840, height: 1872, widths: [640, 960, 1280, 1920, 2560, 3840] },
	'forstberg.webp': { width: 3840, height: 1680, widths: [640, 960, 1280, 1920, 2560, 3840] },
	'niederbauen.webp': { width: 3840, height: 1680, widths: [640, 960, 1280, 1920, 2560, 3840] },
	'pizol.webp': { width: 3840, height: 1216, widths: [640, 960, 1280, 1920, 2560, 3840] },
	'rhine.webp': { width: 3840, height: 1148, widths: [640, 960, 1280, 1920, 2560, 3840] },
	'wallis_dawn.webp': { width: 2560, height: 1280, widths: [640, 960, 1280, 1920, 2560] },
	'wallis_sunrise.webp': { width: 3840, height: 1920, widths: [640, 960, 1280, 1920, 2560, 3840] },
	'zeedijk.webp': { width: 3840, height: 2013, widths: [640, 960, 1280, 1920, 2560, 3840] }
};
